# Generated by Django 2.2.26 on 2022-04-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220402_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
